
[researches]
	#Range: 0.0 ~ 2.147483647E9
	speed = 1.0

[fields]
	#If true, Citizen can works same field to without wait time. Also work in field list by sequentially.
	#If false, use MineColonies' s method.
	newRetrieveMethod = true
	#Range: 5 ~ 15
	farmMaxRange = 5

[jobs]

	[jobs.crafing]
		#craftingTicks = progressMultiplier / craftSkillLevel * hittingTime
		#Range: > 0
		progressMultiplier = 10
		#Range: > 0
		hittingTime = 3

	[jobs.sifter]
		#siftingTicks = progressMultiplier - strengthLevel
		#Range: > 0
		progressMultiplier = 50

	[jobs.farmer]
		#finalDelay = workDelay - (skillDivider * staminaLevel)
		#Range: > 0
		workDelay = 40
		#Range: 1.0 ~ 2.147483647E9
		skillDivider = 2.0
		#if harvested count reached to this, farmer will go to dump
		#Range: > 64
		actionsDoneUntilDumping = 256
		#whether plant seed after hoeing dirt
		plantAfterHoe = true
		#whether plant seed after harvest crop
		plantAfterHarvest = true

	[jobs.structure]
		#If this is off, Builders will requests 'Leaves' on needed it when build.
		leavesFree = true

[citizens]
	disableMourn = false

