debug = false
disable_crowdin = false
check_for_updates = true

[activations.d507ae6f-106c-3257-bea1-a1f3de242b7d]
toggle = false
type = "INHERIT"
[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[activations.46927964-3207-377a-84d7-26a82d52be1e]
toggle = false
type = "INHERIT"
key_bindings = []


[addons.pv-addon-soundphysics]
mic_reverb = false
mic_reverb_volume = 1.0
enabled = true

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -58.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 2.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = true
stereo_capture = true

[voice.volumes.broadcast]
volume = 1.0
[voice.volumes.source_aff47226-a704-4598-9aa8-dab57ddf67a0]
volume = 2.0
[voice.volumes.proximity]
volume = 2.0
[voice.volumes.whisper]
volume = 1.0
[voice.volumes.groups]
volume = 1.0
[voice.volumes.priority]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
mute_player_on_direct = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true
jitter_packet_delay = 3
al_playback_buffers = 5

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
broadcast = "OFF"
proximity = "OFF"
whisper = "OFF"
groups = "WHEN_TALKING"
priority = "OFF"
